name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 21 * * *"
  workflow_dispatch:

jobs:
  sleep:
    runs-on: self-hosted
    name: sleep
    steps:
      - name: first step
        run: sleep 10s
      - name: second step
        run: sleep 10s
      - name: third step
        run: sleep 10s
  build:
    runs-on: self-hosted
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "generated"
          git push
