name: Test Workflow
on:
  workflow_dispatch:
jobs:
  job1:
    runs-on: self-hosted
    name: job 1
    steps:
      - name: step 1.1
        run: sleep 10s
      - name: step 1.2
        run: sleep 10s
      - name: step 1.3
        run: sleep 10s
  job2:
    runs-on: self-hosted
    name: job 2
    steps:
      - name: step 2.1
        run: sleep 10s
      - name: step 2.2
        run: sleep 10s
      - name: step 2.3
        run: sleep 10s
